"""astrbot_plugin_neteasemusic 的上游音乐 API 客户端包（自 core/api.py 拆分）。

子模块划分（原文件的分段注释 → 模块）：
    _core          常量、复用 HTTP 会话、错误处理、基础请求
    _normalize     归一化
    _resolve_link  短链展开（163cn.tv → music.163.com）
    _search        搜索
    _song          歌曲
    _comment       评论、逐字歌词 / 评论扩展
    _playlist      歌单 / 榜单、相似歌单 / 榜单 / 新碟 / 电台
    _user          推荐 / 用户（需登录）、签到 / 云盘 / 最近（需登录）、红心（需登录）
    _artist_mv     歌手 / 专辑 / MV、MV
    _account       登录、账号高档位特权（auto 音质自适应用）

本包对外符号与拆分前的 core/api.py 完全一致（``from ..core.api import X`` 与
``api.X`` 的既有用法不受影响）；模块级状态（HTTP 会话、设备 Cookie、特权缓存）
由 ``_core`` / 对应子模块持有，外部一律通过函数访问。
"""

from ._account import (
    _PRIVILEGE_CACHE_MAX,
    _PRIVILEGE_CACHE_TTL_SEC,
    _now_ts,
    _privilege_cache,
    clear_privilege_cache,
    has_high_quality_privilege,
    login_status,
    logout,
    qr_check,
    qr_create,
    qr_key,
    vip_info,
)
from ._artist_mv import (
    album_detail,
    artist_top_songs,
    mv_detail,
    mv_url,
    search_mv,
)
from ._comment import (
    _comments_for,
    _comments_from_body,
    _normalize_comment,
    comment,
    comment_album,
    comment_playlist,
    lyric_new,
)
from ._core import (
    API_TIMEOUT_SEC,
    ERR_MESSAGES,
    SHORT_LINK_TIMEOUT_SEC,
    USER_AGENT,
    ApiError,
    _cfg,
    _cfg_getter,
    _err_msg_for,
    _get_base,
    _get_cookie,
    _get_session,
    _handle_response,
    _num,
    _opt_int,
    _query_safe_params,
    _session,
    as_int,
    close_session,
    get_session,
    request,
    set_config_getter,
)
from ._normalize import (
    _collect,
    _duration_text,
    _norm_album,
    _norm_artists,
    _norm_fee,
    _normalize_playlist,
    _normalize_song,
)
from ._playlist import (
    album_newest,
    banner,
    dj_recommend,
    highquality_playlists,
    new_songs,
    playlist_cats,
    playlist_detail,
    playlist_hot_tags,
    playlist_tracks,
    simi_playlists,
    top_album,
    top_artists,
    top_detail,
    top_mv,
    top_playlists,
    toplist,
    toplist_artist,
)
from ._resolve_link import (
    SHORT_LINK_RE,
    _follow_redirect,
    expand_short_links,
)
from ._search import (
    hot_search,
    search,
    search_albums,
    search_artists,
    search_playlists,
    search_suggest,
)
from ._song import (
    lyric,
    related_playlists,
    simi_songs,
    song_detail,
    song_url_best,
    song_url_v1,
)
from ._user import (
    daily_signin,
    daily_songs,
    history_recommend_songs,
    like,
    likelist,
    personal_fm,
    recommend_newsong,
    recommend_playlists,
    record_recent_song,
    song_like_check,
    user_cloud,
    user_playlist,
    user_record,
)

__all__ = [
    "API_TIMEOUT_SEC",
    "ApiError",
    "ERR_MESSAGES",
    "SHORT_LINK_RE",
    "SHORT_LINK_TIMEOUT_SEC",
    "USER_AGENT",
    "_PRIVILEGE_CACHE_MAX",
    "_PRIVILEGE_CACHE_TTL_SEC",
    "_cfg",
    "_cfg_getter",
    "_collect",
    "_comments_for",
    "_comments_from_body",
    "_duration_text",
    "_err_msg_for",
    "_follow_redirect",
    "_get_base",
    "_get_cookie",
    "_get_session",
    "_handle_response",
    "_norm_album",
    "_norm_artists",
    "_norm_fee",
    "_normalize_comment",
    "_normalize_playlist",
    "_normalize_song",
    "_now_ts",
    "_num",
    "_opt_int",
    "_privilege_cache",
    "_query_safe_params",
    "_session",
    "album_detail",
    "album_newest",
    "artist_top_songs",
    "as_int",
    "banner",
    "clear_privilege_cache",
    "close_session",
    "comment",
    "comment_album",
    "comment_playlist",
    "daily_signin",
    "daily_songs",
    "dj_recommend",
    "expand_short_links",
    "get_session",
    "has_high_quality_privilege",
    "highquality_playlists",
    "history_recommend_songs",
    "hot_search",
    "like",
    "likelist",
    "login_status",
    "logout",
    "lyric",
    "lyric_new",
    "mv_detail",
    "mv_url",
    "new_songs",
    "personal_fm",
    "playlist_cats",
    "playlist_detail",
    "playlist_hot_tags",
    "playlist_tracks",
    "qr_check",
    "qr_create",
    "qr_key",
    "recommend_newsong",
    "recommend_playlists",
    "record_recent_song",
    "related_playlists",
    "request",
    "search",
    "search_albums",
    "search_artists",
    "search_mv",
    "search_playlists",
    "search_suggest",
    "set_config_getter",
    "simi_playlists",
    "simi_songs",
    "song_detail",
    "song_like_check",
    "song_url_best",
    "song_url_v1",
    "top_album",
    "top_artists",
    "top_detail",
    "top_mv",
    "top_playlists",
    "toplist",
    "toplist_artist",
    "user_cloud",
    "user_playlist",
    "user_record",
    "vip_info",
]
